module.exports = {
    ERROR_PASSWORD: "Mật khẩu không hợp lệ",
    NOTITY_LOGIN: "Sai mật khẩu, bạn chỉ có 3 lần đăng nhập",
    SUCCESS_GET_USER_LIST: "Thực hiện lấy danh sách thành công",
    SUCCESS_GET_USER: "Lấy thành công user",
    SUCCESS_EDIT_USER: "Đã chỉnh sửa thành công user",
    SUCCESS_DELETE_USER: "Xóa thành công user",
    ERROR_PASSWORD_USERNAME_EMPTY: "Username hoặc Password không được bỏ trống",
    ERROR_PASSWORD_UNCORRECT: "Password nhập vào không chính xác",
    ERROR_USERNAME_UNCORRECT: "Username nhập vào không chính xác",
    NOTIFY_TOKEN_EXP: "Mã đã hết hạn, vui lòng nhập lại mã mới",
    SUCCESS_CONFIRM: "Xác thực mã thành công, vui lòng thực hiện bước tiếp theo",
    NOTIFY_CHECK_INFO: "Vui lòng kiểm tra lại thông tin",
    SUCCESS_REGISTER: "Đã đăng ký thành công",
    ERROR_EMAIL_USERNAME_UNCORRECT: "Username hoặc email không hợp lệ, vui lòng nhập lại",
    ERROR_EXCUTE_FAIL: "Thao tác thất bại, vui lòng thực hiện lại",
    ERROR_EXISTS_USER: "User này đã tồn tại",
    ERROR_EXISTS_LISTFRIEND: "Danh sách bạn bè này đã tồn tại",
    NOTIFY_LOGIN_AGAIN: "Vui lòng đăng nhập lại sau 3 phút",
    ERROR_DUPLICATE_DATA: "Dữ liệu trùng, vui lòng thực hiện lại",
    SUCCESS_LOGIN: "Đăng nhập thành công",
    SUCCESS_CHECKEMAIL: "Vui lòng kiểm tra email của bạn",
    SUCCESS_RESETPASSWORD: "Đổi mật khẩu thành công",
    SUCCESS_DELETE_LISTFRIENDS: "Xóa thành công bạn bè",
    SUCCESS_UPDATE_LISTFRIENDS: "Cập nhật thành công bạn bè",
    SUCCESS_CREATE: "Tạo mới thành công",
    SUCCESS_GET: "Lấy danh sách thành công",
    SUCCESS_UPDATE_MATCHES: "Cập nhật trạng thái thành công (join or exit) của user",
    SUCCESS_UPDATE_MATCHES_RESULT: "Cập nhật thành công kết quả của trận đấu",
    SUCCESS_DELETE_MATCHES: "Xóa thành công phòng chơi",
    NOTIFY_LIST_EMPTY: "Danh sách trống, không thể thực hiện thao tác",
    NOTIFY_FULLROOM: "Phòng chơi đã đủ người, vui lòng chọn phòng khác",
    ERROR_FIND_USER: "Không thể tìm thấy user này",
    ERROR_EXISTS: "Username đã tồn tại, vui lòng chọn username khác",
    ERROR_NOT_EXISTS: "User không tồn tại",
    SUCCESS_UPDATE_SCORE: "Cập nhật điểm thành công"
}